import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'settings': 'Settings',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'share': 'Share',
      'reset': 'Reset',
      'done': 'Done',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'error': 'Error',
      'success': 'Done',
      'loading': 'Loading...',
      'no_data': 'No data yet.',
      'no_history': 'No history yet.',
      'history': 'History',
      'stats': 'Statistics',
      'refresh': 'Refresh',
      'bpm': 'BPM',
      'history_item_subtitle': 'screen: @screen\nroute: @route',
      'total_events': 'Total Events',
      'today_events': 'Today Events',
      'week_events': 'This Week Events',
      'unique_routes': 'Unique Routes',
      'unique_screens': 'Unique Screens',
      'top_events': 'Top Events',

      'open_history': 'History',
      'open_stats': 'Stats',
      'clear_all': 'Clear All',
      'copy': 'Copy',

      'settings_title': 'Settings',
      'settings_page': 'Settings',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'about': 'About',
      'version': 'Version',
      'rate_app': 'Rate this App',
      'privacy_policy': 'Privacy Policy',
      'remove_ads': 'Remove Ads',
      'premium_title': 'Premium',
      'premium_subtitle': 'Go ad-free and unlock every feature.',
      'premium_benefits': 'Premium Benefits',
      'premium_benefit_remove_ads': 'Remove ads',
      'premium_benefit_unlimited': 'Use all features without limits',
      'premium_benefit_statistics': 'View additional statistics',
      'premium_plan_title': 'Choose a plan',
      'premium_plan_weekly': 'Weekly',
      'premium_plan_weekly_desc': '1 week premium access',
      'premium_plan_monthly': 'Monthly',
      'premium_plan_monthly_desc': '30 days premium access',
      'premium_plan_yearly': 'Yearly',
      'premium_plan_yearly_desc': '365 days premium access',
      'premium_purchase': 'Start Premium',
      'premium_restore': 'Restore purchases',
      'premium_owned': 'Premium is active',
      'premium_purchase_note': 'If your payment is completed, purchase will be restored automatically after app restart.',
      'purchase_error': "We couldn't complete your purchase. Please try again in a moment.",
      'purchase_unavailable': "In-app purchases aren't available right now. Please try again in a moment.",
      'purchase_failed': "We couldn't complete your purchase. Please try again in a moment.",
      'restore_error': "We couldn't restore your purchase yet. Please try again in a moment.",
      'purchase_success': 'Purchase complete.',
      'premium_ready': 'Premium is ready.',
      'dev_premium_on': '[DEV] Premium OFF → ON',
      'dev_premium_off': '[DEV] Premium ON → OFF',
      'send_feedback': 'Send Feedback',
      'more_apps': 'See More Apps',

      'app_name': 'Metronome',
      'haptic': 'Vibration',
      'sound': 'Sound',
      'play': 'Play',
      'stop': 'Stop',
      'beat_pattern': 'Beat Pattern',
      'tap_tempo': 'Tap Tempo',
      'tap_for_bpm': 'Tap the button to find the BPM',
      'tap_count_one': '1 tap — tap once more to measure',
      'tap_count_many': '@count taps',
      'guide': 'Guide',
      'guide_title': 'How to use the metronome',
      'guide_tip_1_title': '1) Set the BPM',
      'guide_tip_1_desc':
          'Use the slider or +/- buttons to set the tempo you want.',
      'guide_tip_2_title': '2) Choose a beat pattern',
      'guide_tip_2_desc':
          'Change the beat pattern to match the style you want to practice.',
      'guide_tip_3_title': '3) Save your preference',
      'guide_tip_3_desc':
          'Turn vibration on or off and keep your preferred tempo and beat settings.',
      'guide_tip_4_title': '4) Review history',
      'guide_tip_4_desc':
          'Check your metronome usage in History and Stats.',
      'guide_footer':
          'You can adjust everything in one tap from Home and use it immediately.',
    },
    'ko': {
      'settings': '설정',
      'save': '저장',
      'cancel': '취소',
      'delete': '삭제',
      'edit': '편집',
      'share': '공유',
      'reset': '초기화',
      'done': '완료',
      'ok': '확인',
      'yes': '예',
      'no': '아니요',
      'error': '오류',
      'success': '완료됐어요',
      'loading': '불러오는 중이에요',
      'no_data': '아직 내용이 없어요',
      'no_history': '아직 기록이 없어요',
      'history': '기록',
      'stats': '통계',
      'refresh': '새로고침',
      'bpm': 'BPM',
      'history_item_subtitle': '화면: @screen / 경로: @route',
      'total_events': '총 이벤트',
      'today_events': '오늘',
      'week_events': '이번 주',
      'unique_routes': '고유 경로',
      'unique_screens': '고유 화면',
      'top_events': '상위 이벤트',
      'open_history': '기록',
      'open_stats': '통계',
      'clear_all': '전체 삭제',
      'copy': '복사',
      'settings_title': '설정',
      'settings_page': '설정',
      'dark_mode': '다크 모드',
      'language': '언어',
      'about': '앱 정보',
      'version': '버전',
      'rate_app': '앱 평가하기',
      'privacy_policy': '개인정보 처리방침',
      'remove_ads': '광고 제거',
      'premium_title': '프리미엄',
      'premium_subtitle': '광고 없이 모든 기능을 쓸 수 있어요.',
      'premium_benefits': '프리미엄 혜택',
      'premium_benefit_remove_ads': '광고 제거',
      'premium_benefit_unlimited': '모든 기능 잠금 해제',
      'premium_benefit_statistics': '추가 통계 보기',
      'premium_plan_title': '요금제 선택',
      'premium_plan_weekly': '주간',
      'premium_plan_weekly_desc': '7일 프리미엄',
      'premium_plan_monthly': '월간',
      'premium_plan_monthly_desc': '30일 프리미엄',
      'premium_plan_yearly': '연간',
      'premium_plan_yearly_desc': '365일 프리미엄',
      'premium_purchase': '구매하기',
      'premium_restore': '구매 내역 복원',
      'premium_owned': '프리미엄이 활성화됐어요',
      'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
      'purchase_error': '구매를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
      'purchase_unavailable': '지금은 인앱 결제를 이용하기 어려워요. 잠시 후 다시 시도해 주세요.',
      'purchase_failed': '결제를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
      'restore_error': '구매 내역을 아직 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
      'purchase_success': '구매를 완료했어요.',
      'premium_ready': '프리미엄을 바로 쓸 수 있어요.',
      'dev_premium_on': '[DEV] 프리미엄 OFF → ON',
      'dev_premium_off': '[DEV] 프리미엄 ON → OFF',
      'send_feedback': '의견 보내기',
      'more_apps': '다른 앱 보기',
      'app_name': '메트로놈',
      'haptic': '진동 피드백',
      'sound': '사운드',
      'play': '재생',
      'stop': '정지',
      'beat_pattern': '박자 패턴',
      'tap_tempo': '탭 템포',
      'tap_for_bpm': '버튼을 탭하면 BPM을 잴 수 있어요',
      'tap_count_one': '1번 탭 — 한 번 더 탭해야 측정돼요',
      'tap_count_many': '@count번 탭',
      'guide': '사용법',
      'guide_title': '메트로놈 사용법',
      'guide_tip_1_title': '1) BPM 설정',
      'guide_tip_1_desc': '슬라이더나 +/- 버튼으로 원하는 템포를 맞춰요.',
      'guide_tip_2_title': '2) 박자 패턴 선택',
      'guide_tip_2_desc': '박자를 바꿔 연습하고 싶은 스타일에 맞춰요.',
      'guide_tip_3_title': '3) 설정 저장',
      'guide_tip_3_desc': '진동을 켜거나 끄고, 원하는 템포와 박자를 그대로 유지해요.',
      'guide_tip_4_title': '4) 기록 확인',
      'guide_tip_4_desc': '기록과 통계 페이지에서 메트로놈 사용 현황을 볼 수 있어요.',
      'guide_footer': '홈에서 한 번의 탭으로 모든 설정을 바꾸고 바로 사용할 수 있어요.',
    },
  };
}



