import 'dart:ui';

import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
    Locale('ja'),
    Locale('de'),
    Locale('ru'),
    Locale('fr'),
    Locale('es'),
    Locale('pt'),
    Locale('id'),
    Locale('zh'),
    Locale('ar'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': _en,
    'ko': _ko,
    'ja': _ja,
    'de': _de,
    'ru': _ru,
    'fr': _fr,
    'es': _es,
    'pt': _pt,
    'id': _id,
    'zh': _zh,
    'ar': _ar,
  };

  static const Map<String, String> _en = {
    'settings': 'Settings',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'share': 'Share',
    'reset': 'Reset',
    'done': 'Done',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'error': 'Error',
    'success': 'Done',
    'loading': 'Loading...',
    'no_data': 'No data yet.',
    'no_history': 'No history yet.',
    'history': 'History',
    'stats': 'Statistics',
    'refresh': 'Refresh',
    'bpm': 'BPM',
    'history_item_subtitle': 'screen: @screen\nroute: @route',
    'total_events': 'Total Events',
    'today_events': 'Today Events',
    'week_events': 'This Week Events',
    'unique_routes': 'Unique Routes',
    'unique_screens': 'Unique Screens',
    'top_events': 'Top Events',
    'open_history': 'History',
    'open_stats': 'Stats',
    'clear_all': 'Clear All',
    'copy': 'Copy',
    'settings_title': 'Settings',
    'settings_page': 'Settings',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'about': 'About',
    'version': 'Version',
    'rate_app': 'Rate this App',
    'privacy_policy': 'Privacy Policy',
    'remove_ads': 'Remove Ads',
    'premium_title': 'Premium',
    'premium_subtitle': 'Go ad-free and unlock every feature.',
    'premium_benefits': 'Premium Benefits',
    'premium_benefit_remove_ads': 'Remove ads',
    'premium_benefit_unlimited': 'Use all features without limits',
    'premium_benefit_statistics': 'View additional statistics',
    'premium_plan_title': 'Choose a plan',
    'premium_plan_weekly': 'Weekly',
    'premium_plan_weekly_desc': '1 week premium access',
    'premium_plan_monthly': 'Monthly',
    'premium_plan_monthly_desc': '30 days premium access',
    'premium_plan_yearly': 'Yearly',
    'premium_plan_yearly_desc': '365 days premium access',
    'premium_purchase': 'Start Premium',
    'premium_restore': 'Restore purchases',
    'premium_owned': 'Premium is active',
    'premium_purchase_note':
        'If your payment is completed, purchase will be restored automatically after app restart.',
    'purchase_error':
        'We couldn\'t complete your purchase. Please try again in a moment.',
    'purchase_unavailable':
        'In-app purchases aren\'t available right now. Please try again in a moment.',
    'purchase_failed':
        'We couldn\'t complete your purchase. Please try again in a moment.',
    'restore_error':
        'We couldn\'t restore your purchase yet. Please try again in a moment.',
    'purchase_success': 'Purchase complete.',
    'premium_ready': 'Premium is ready.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Send Feedback',
    'more_apps': 'See More Apps',
    'app_name': 'Metronome',
    'haptic': 'Vibration',
    'sound': 'Sound',
    'play': 'Play',
    'stop': 'Stop',
    'beat_pattern': 'Beat Pattern',
    'tap_tempo': 'Tap Tempo',
    'tap_for_bpm': 'Tap the button to find the BPM',
    'tap_count_one': '1 tap — tap once more to measure',
    'tap_count_many': '@count taps',
    'guide': 'Guide',
    'guide_title': 'How to use the metronome',
    'guide_tip_1_title': '1) Set the BPM',
    'guide_tip_1_desc':
        'Use the slider or +/- buttons to set the tempo you want.',
    'guide_tip_2_title': '2) Choose a beat pattern',
    'guide_tip_2_desc':
        'Change the beat pattern to match the style you want to practice.',
    'guide_tip_3_title': '3) Save your preference',
    'guide_tip_3_desc':
        'Turn vibration on or off and keep your preferred tempo and beat settings.',
    'guide_tip_4_title': '4) Review history',
    'guide_tip_4_desc': 'Check your metronome usage in History and Stats.',
    'guide_tip_5_title': '5) Subdivisions',
    'guide_tip_5_desc':
        'Split each beat into eighth notes, triplets, or sixteenth notes for precise practice.',
    'guide_tip_6_title': '6) Accent patterns',
    'guide_tip_6_desc':
        'Tap any beat indicator to cycle through strong, normal, and mute accents.',
    'guide_tip_7_title': '7) Drag to change BPM',
    'guide_tip_7_desc':
        'Swipe up or down on the BPM display to quickly adjust the tempo.',
    'guide_footer':
        'You can adjust everything in one tap from Home and use it immediately.',
    'subdivision': 'Subdivision',
    'drag_bpm_hint': '↕ Drag to adjust',
    'taps_unit': ' taps',
  };

  static const Map<String, String> _ko = {
    'settings': '설정',
    'save': '저장',
    'cancel': '취소',
    'delete': '삭제',
    'edit': '편집',
    'share': '공유',
    'reset': '초기화',
    'done': '완료',
    'ok': '확인',
    'yes': '예',
    'no': '아니요',
    'error': '오류',
    'success': '완료됐어요',
    'loading': '불러오는 중이에요',
    'no_data': '아직 내용이 없어요',
    'no_history': '아직 기록이 없어요',
    'history': '기록',
    'stats': '통계',
    'refresh': '새로고침',
    'bpm': 'BPM',
    'history_item_subtitle': '화면: @screen / 경로: @route',
    'total_events': '총 이벤트',
    'today_events': '오늘',
    'week_events': '이번 주',
    'unique_routes': '고유 경로',
    'unique_screens': '고유 화면',
    'top_events': '상위 이벤트',
    'open_history': '기록',
    'open_stats': '통계',
    'clear_all': '전체 삭제',
    'copy': '복사',
    'settings_title': '설정',
    'settings_page': '설정',
    'dark_mode': '다크 모드',
    'language': '언어',
    'about': '앱 정보',
    'version': '버전',
    'rate_app': '앱 평가하기',
    'privacy_policy': '개인정보 처리방침',
    'remove_ads': '광고 제거',
    'premium_title': '프리미엄',
    'premium_subtitle': '광고 없이 모든 기능을 쓸 수 있어요.',
    'premium_benefits': '프리미엄 혜택',
    'premium_benefit_remove_ads': '광고 제거',
    'premium_benefit_unlimited': '모든 기능 잠금 해제',
    'premium_benefit_statistics': '추가 통계 보기',
    'premium_plan_title': '요금제 선택',
    'premium_plan_weekly': '주간',
    'premium_plan_weekly_desc': '7일 프리미엄',
    'premium_plan_monthly': '월간',
    'premium_plan_monthly_desc': '30일 프리미엄',
    'premium_plan_yearly': '연간',
    'premium_plan_yearly_desc': '365일 프리미엄',
    'premium_purchase': '구매하기',
    'premium_restore': '구매 내역 복원',
    'premium_owned': '프리미엄이 활성화됐어요',
    'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
    'purchase_error': '구매를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
    'purchase_unavailable': '지금은 인앱 결제를 이용하기 어려워요. 잠시 후 다시 시도해 주세요.',
    'purchase_failed': '결제를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
    'restore_error': '구매 내역을 아직 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
    'purchase_success': '구매를 완료했어요.',
    'premium_ready': '프리미엄을 바로 쓸 수 있어요.',
    'dev_premium_on': '[DEV] 프리미엄 OFF → ON',
    'dev_premium_off': '[DEV] 프리미엄 ON → OFF',
    'send_feedback': '의견 보내기',
    'more_apps': '다른 앱 보기',
    'app_name': '메트로놈',
    'haptic': '진동 피드백',
    'sound': '사운드',
    'play': '재생',
    'stop': '정지',
    'beat_pattern': '박자 패턴',
    'tap_tempo': '탭 템포',
    'tap_for_bpm': '버튼을 탭하면 BPM을 잴 수 있어요',
    'tap_count_one': '1번 탭 — 한 번 더 탭해야 측정돼요',
    'tap_count_many': '@count번 탭',
    'guide': '사용법',
    'guide_title': '메트로놈 사용법',
    'guide_tip_1_title': '1) BPM 설정',
    'guide_tip_1_desc': '슬라이더나 +/- 버튼으로 원하는 템포를 맞춰요.',
    'guide_tip_2_title': '2) 박자 패턴 선택',
    'guide_tip_2_desc': '박자를 바꿔 연습하고 싶은 스타일에 맞춰요.',
    'guide_tip_3_title': '3) 설정 저장',
    'guide_tip_3_desc': '진동을 켜거나 끄고, 원하는 템포와 박자를 그대로 유지해요.',
    'guide_tip_4_title': '4) 기록 확인',
    'guide_tip_4_desc': '기록과 통계 페이지에서 메트로놈 사용 현황을 볼 수 있어요.',
    'guide_tip_5_title': '5) 서브디비전',
    'guide_tip_5_desc': '각 비트를 8분음표, 3연음, 16분음표로 나눠 정밀하게 연습해요.',
    'guide_tip_6_title': '6) 악센트 패턴',
    'guide_tip_6_desc': '비트 표시기를 탭하면 강·보통·음소거 악센트를 바꿀 수 있어요.',
    'guide_tip_7_title': '7) 드래그로 BPM 변경',
    'guide_tip_7_desc': 'BPM 표시 영역을 위아래로 스와이프하면 빠르게 템포를 조절할 수 있어요.',
    'guide_footer': '홈에서 한 번의 탭으로 모든 설정을 바꾸고 바로 사용할 수 있어요.',
    'subdivision': '서브디비전',
    'drag_bpm_hint': '↕ 드래그하여 조절',
    'taps_unit': '탭',
  };

  static const Map<String, String> _ja = {
    'settings': '設定',
    'save': '保存',
    'cancel': 'キャンセル',
    'delete': '削除',
    'edit': '編集',
    'share': '共有',
    'reset': 'リセット',
    'done': '完了',
    'ok': 'OK',
    'yes': 'はい',
    'no': 'いいえ',
    'error': 'エラー',
    'success': '完了',
    'loading': '読み込み中...',
    'no_data': 'まだデータがありません。',
    'no_history': 'まだ履歴がありません。',
    'history': '履歴',
    'stats': '統計',
    'refresh': '更新',
    'bpm': 'BPM',
    'history_item_subtitle': '画面: @screen\nルート: @route',
    'total_events': '合計イベント',
    'today_events': '今日のイベント',
    'week_events': '今週のイベント',
    'unique_routes': '固有ルート',
    'unique_screens': '固有画面',
    'top_events': '上位イベント',
    'open_history': '履歴',
    'open_stats': '統計',
    'clear_all': 'すべて削除',
    'copy': 'コピー',
    'settings_title': '設定',
    'settings_page': '設定',
    'dark_mode': 'ダークモード',
    'language': '言語',
    'about': 'アプリ情報',
    'version': 'バージョン',
    'rate_app': 'アプリを評価',
    'privacy_policy': 'プライバシーポリシー',
    'remove_ads': '広告を削除',
    'premium_title': 'プレミアム',
    'premium_subtitle': '広告なしですべての機能をロック解除しましょう。',
    'premium_benefits': 'プレミアム特典',
    'premium_benefit_remove_ads': '広告を削除',
    'premium_benefit_unlimited': 'すべての機能を制限なく使用する',
    'premium_benefit_statistics': '追加の統計を表示する',
    'premium_plan_title': 'プランを選択してください',
    'premium_plan_weekly': '週間',
    'premium_plan_weekly_desc': '1週間のプレミアムアクセス',
    'premium_plan_monthly': '月',
    'premium_plan_monthly_desc': '30 日間のプレミアム アクセス',
    'premium_plan_yearly': '毎年',
    'premium_plan_yearly_desc': '365 日のプレミアムアクセス',
    'premium_purchase': 'プレミアムを始める',
    'premium_restore': '購入を復元',
    'premium_owned': 'Premiumが有効です',
    'premium_purchase_note': '支払いが完了すると、アプリを再起動すると自動的に購入が復元されます。',
    'purchase_error': '購入を完了できませんでした。少し後でもう一度お試しください。',
    'purchase_unavailable': '現在、アプリ内購入は利用できません。しばらくしてからもう一度お試しください。',
    'purchase_failed': '購入を完了できませんでした。少し後でもう一度お試しください。',
    'restore_error': '購入を復元できませんでした。少し後でもう一度お試しください。',
    'purchase_success': '購入完了。',
    'premium_ready': 'プレミアムが完成しました。',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'フィードバックを送信',
    'more_apps': '他のアプリを見る',
    'app_name': 'メトロノーム',
    'haptic': 'バイブレーション',
    'sound': 'サウンド',
    'play': '再生',
    'stop': '停止',
    'beat_pattern': 'ビートパターン',
    'tap_tempo': 'タップテンポ',
    'tap_for_bpm': 'ボタンをタップしてBPMを確認します',
    'tap_count_one': '1 タップ — もう一度タップして測定します',
    'tap_count_many': '@count タップ',
    'guide': 'ガイド',
    'guide_title': 'メトロノームの使い方',
    'guide_tip_1_title': '1) BPMを設定する',
    'guide_tip_1_desc': 'スライダーまたは +/- ボタンを使用して、希望のテンポを設定します。',
    'guide_tip_2_title': '2) ビートパターンを選択します',
    'guide_tip_2_desc': '練習したいスタイルに合わせてビートパターンを変更します。',
    'guide_tip_3_title': '3) 設定を保存します',
    'guide_tip_3_desc': '振動をオンまたはオフにして、お好みのテンポとビートの設定を維持します。',
    'guide_tip_4_title': '4) レビュー履歴',
    'guide_tip_4_desc': '履歴と統計でメトロノームの使用状況を確認します。',
    'guide_tip_5_title': '5) 細分化',
    'guide_tip_5_desc': '正確な練習のために、各ビートを 8 分音符、3 連符、または 16 分音符に分割します。',
    'guide_tip_6_title': '6) アクセントパターン',
    'guide_tip_6_desc':
        'ビートインジケーターをタップして、強いアクセント、通常のアクセント、ミュートアクセントを順番に切り替えます。',
    'guide_tip_7_title': '7) ドラッグしてBPMを変更します',
    'guide_tip_7_desc': 'BPM 表示を上下にスワイプすると、テンポをすばやく調整できます。',
    'guide_footer': 'ホームからワンタップですべてを調整し、すぐに使用できます。',
    'subdivision': '区画',
    'drag_bpm_hint': '↕ ドラッグして調整します',
    'taps_unit': ' タップする',
  };

  static const Map<String, String> _de = {
    'settings': 'Einstellungen',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'delete': 'Löschen',
    'edit': 'Bearbeiten',
    'share': 'Teilen',
    'reset': 'Zurücksetzen',
    'done': 'Erledigt',
    'ok': 'OK',
    'yes': 'Ja',
    'no': 'Nein',
    'error': 'Fehler',
    'success': 'Erledigt',
    'loading': 'Lädt...',
    'no_data': 'Noch keine Daten.',
    'no_history': 'Noch kein Verlauf.',
    'history': 'Verlauf',
    'stats': 'Statistik',
    'refresh': 'Aktualisieren',
    'bpm': 'BPM',
    'history_item_subtitle': 'Bildschirm: @screen\nRoute: @route',
    'total_events': 'Ereignisse gesamt',
    'today_events': 'Ereignisse heute',
    'week_events': 'Veranstaltungen dieser Woche',
    'unique_routes': 'Einmalige Routen',
    'unique_screens': 'Einmalige Bildschirme',
    'top_events': 'Top-Ereignisse',
    'open_history': 'Verlauf',
    'open_stats': 'Statistik',
    'clear_all': 'Alles löschen',
    'copy': 'Kopieren',
    'settings_title': 'Einstellungen',
    'settings_page': 'Einstellungen',
    'dark_mode': 'Dunkler Modus',
    'language': 'Sprache',
    'about': 'Info',
    'version': 'Version',
    'rate_app': 'App bewerten',
    'privacy_policy': 'Datenschutz',
    'remove_ads': 'Werbung entfernen',
    'premium_title': 'Premium',
    'premium_subtitle':
        'Werden Sie werbefrei und schalten Sie alle Funktionen frei.',
    'premium_benefits': 'Premium-Vorteile',
    'premium_benefit_remove_ads': 'Werbung entfernen',
    'premium_benefit_unlimited':
        'Nutzen Sie alle Funktionen ohne Einschränkungen',
    'premium_benefit_statistics': 'Weitere Statistiken anzeigen',
    'premium_plan_title': 'Wählen Sie einen Plan',
    'premium_plan_weekly': 'Woche',
    'premium_plan_weekly_desc': '1 Woche Premium-Zugang',
    'premium_plan_monthly': 'Monat',
    'premium_plan_monthly_desc': '30 Tage Premium-Zugang',
    'premium_plan_yearly': 'Jährlich',
    'premium_plan_yearly_desc': '365 Tage Premium-Zugang',
    'premium_purchase': 'Starten Sie Premium',
    'premium_restore': 'Käufe wiederherstellen',
    'premium_owned': 'Premium ist aktiv',
    'premium_purchase_note':
        'Wenn Ihre Zahlung abgeschlossen ist, wird der Kauf nach dem Neustart der App automatisch wiederhergestellt.',
    'purchase_error':
        'Der Kauf konnte nicht abgeschlossen werden. Bitte später erneut versuchen.',
    'purchase_unavailable':
        'In-App-Käufe sind derzeit nicht verfügbar. Bitte versuchen Sie es gleich noch einmal.',
    'purchase_failed':
        'Der Kauf konnte nicht abgeschlossen werden. Bitte später erneut versuchen.',
    'restore_error':
        'Käufe konnten noch nicht wiederhergestellt werden. Bitte später erneut versuchen.',
    'purchase_success': 'Kauf abgeschlossen.',
    'premium_ready': 'Premium ist fertig.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Feedback senden',
    'more_apps': 'Weitere Apps',
    'app_name': 'Metronom',
    'haptic': 'Vibration',
    'sound': 'Sound',
    'play': 'Abspielen',
    'stop': 'Stop',
    'beat_pattern': 'Beat-Muster',
    'tap_tempo': 'Tippen Sie auf Tempo',
    'tap_for_bpm': 'Tippen Sie auf die Schaltfläche, um den BPM zu finden',
    'tap_count_one': '1 Tipp – tippen Sie noch einmal, um zu messen',
    'tap_count_many': '@count Wasserhähne',
    'guide': 'Anleitung',
    'guide_title': 'Wie man das Metronom benutzt',
    'guide_tip_1_title': '1) Stellen Sie den BPM ein',
    'guide_tip_1_desc':
        'Stellen Sie mit dem Schieberegler oder den +/- Tasten das gewünschte Tempo ein.',
    'guide_tip_2_title': '2) Wählen Sie ein Beat-Muster',
    'guide_tip_2_desc':
        'Ändern Sie das Schlagmuster entsprechend dem Stil, den Sie üben möchten.',
    'guide_tip_3_title': '3) Speichern Sie Ihre Präferenz',
    'guide_tip_3_desc':
        'Schalten Sie die Vibration ein oder aus und behalten Sie Ihre bevorzugten Tempo- und Beat-Einstellungen bei.',
    'guide_tip_4_title': '4) Überprüfen Sie den Verlauf',
    'guide_tip_4_desc':
        'Überprüfen Sie Ihre Metronomnutzung im Verlauf und in den Statistiken.',
    'guide_tip_5_title': '5) Unterteilungen',
    'guide_tip_5_desc':
        'Teilen Sie jeden Schlag zum präzisen Üben in Achtelnoten, Triolen oder Sechzehntelnoten auf.',
    'guide_tip_6_title': '6) Akzentmuster',
    'guide_tip_6_desc':
        'Tippen Sie auf eine beliebige Beat-Anzeige, um zwischen starken, normalen und stummen Akzenten zu wechseln.',
    'guide_tip_7_title': '7) Ziehen Sie, um den BPM zu ändern',
    'guide_tip_7_desc':
        'Wischen Sie auf der BPM-Anzeige nach oben oder unten, um das Tempo schnell anzupassen.',
    'guide_footer':
        'Sie können alles mit einem Fingertipp von der Startseite aus anpassen und sofort verwenden.',
    'subdivision': 'Unterteilung',
    'drag_bpm_hint': '↕ Zum Anpassen ziehen',
    'taps_unit': ' Wasserhähne',
  };

  static const Map<String, String> _ru = {
    'settings': 'Настройки',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'delete': 'Удалить',
    'edit': 'Изменить',
    'share': 'Поделиться',
    'reset': 'Сброс',
    'done': 'Готово',
    'ok': 'OK',
    'yes': 'Да',
    'no': 'Нет',
    'error': 'Ошибка',
    'success': 'Готово',
    'loading': 'Загрузка...',
    'no_data': 'Пока нет данных.',
    'no_history': 'Истории пока нет.',
    'history': 'История',
    'stats': 'Статистика',
    'refresh': 'Обновить',
    'bpm': 'БПМ',
    'history_item_subtitle': 'экран: @screen\nмаршрут: @route',
    'total_events': 'Всего событий',
    'today_events': 'События сегодня',
    'week_events': 'События этой недели',
    'unique_routes': 'Уникальные маршруты',
    'unique_screens': 'Уникальные экраны',
    'top_events': 'Популярные события',
    'open_history': 'История',
    'open_stats': 'Статистика',
    'clear_all': 'Очистить все',
    'copy': 'Копировать',
    'settings_title': 'Настройки',
    'settings_page': 'Настройки',
    'dark_mode': 'Темная тема',
    'language': 'Язык',
    'about': 'О приложении',
    'version': 'Версия',
    'rate_app': 'Оценить приложение',
    'privacy_policy': 'Политика конфиденциальности',
    'remove_ads': 'Убрать рекламу',
    'premium_title': 'Премиум',
    'premium_subtitle': 'Освободитесь от рекламы и разблокируйте все функции.',
    'premium_benefits': 'Премиальные преимущества',
    'premium_benefit_remove_ads': 'Убрать рекламу',
    'premium_benefit_unlimited': 'Используйте все функции без ограничений',
    'premium_benefit_statistics': 'Посмотреть дополнительную статистику',
    'premium_plan_title': 'Выберите план',
    'premium_plan_weekly': 'Неделя',
    'premium_plan_weekly_desc': 'Премиум-доступ на 1 неделю',
    'premium_plan_monthly': 'Месяц',
    'premium_plan_monthly_desc': 'Премиум-доступ на 30 дней',
    'premium_plan_yearly': 'Ежегодно',
    'premium_plan_yearly_desc': 'Премиум-доступ на 365 дней',
    'premium_purchase': 'Начать Премиум',
    'premium_restore': 'Восстановить покупки',
    'premium_owned': 'Premium активен',
    'premium_purchase_note':
        'Если ваш платеж будет завершен, покупка будет восстановлена автоматически после перезапуска приложения.',
    'purchase_error': 'Не удалось завершить покупку. Попробуйте позже.',
    'purchase_unavailable':
        'Покупки в приложении сейчас недоступны. Пожалуйста, повторите попытку через минуту.',
    'purchase_failed': 'Не удалось завершить покупку. Попробуйте позже.',
    'restore_error': 'Не удалось восстановить покупку. Попробуйте позже.',
    'purchase_success': 'Покупка завершена.',
    'premium_ready': 'Премиум готов.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Отправить отзыв',
    'more_apps': 'Другие приложения',
    'app_name': 'Метроном',
    'haptic': 'Вибрация',
    'sound': 'Звук',
    'play': 'Играть',
    'stop': 'Стоп',
    'beat_pattern': 'Битовый паттерн',
    'tap_tempo': 'Нажмите «Темп»',
    'tap_for_bpm': 'Нажмите кнопку, чтобы найти BPM',
    'tap_count_one': '1 касание — коснитесь еще раз, чтобы измерить',
    'tap_count_many': '@count краны',
    'guide': 'Гид',
    'guide_title': 'Как пользоваться метрономом',
    'guide_tip_1_title': '1) Установите BPM',
    'guide_tip_1_desc':
        'Используйте ползунок или кнопки +/-, чтобы установить нужный темп.',
    'guide_tip_2_title': '2) Выберите ритм-паттерн',
    'guide_tip_2_desc':
        'Измените рисунок ритма, чтобы он соответствовал стилю, который вы хотите практиковать.',
    'guide_tip_3_title': '3) Сохраните свои предпочтения',
    'guide_tip_3_desc':
        'Включите или выключите вибрацию и сохраните предпочитаемые настройки темпа и ритма.',
    'guide_tip_4_title': '4) История просмотра',
    'guide_tip_4_desc':
        'Проверьте использование метронома в разделе «История» и «Статистика».',
    'guide_tip_5_title': '5) Подразделения',
    'guide_tip_5_desc':
        'Разделите каждую долю на восьмые, триоли или шестнадцатые для более точной практики.',
    'guide_tip_6_title': '6) Акцентные модели',
    'guide_tip_6_desc':
        'Коснитесь любого индикатора доли, чтобы переключаться между сильными, нормальными и приглушенными акцентами.',
    'guide_tip_7_title': '7) Перетащите, чтобы изменить BPM',
    'guide_tip_7_desc':
        'Проведите вверх или вниз по дисплею BPM, чтобы быстро отрегулировать темп.',
    'guide_footer':
        'Вы можете настроить все одним нажатием на главном экране и сразу же использовать.',
    'subdivision': 'Подразделение',
    'drag_bpm_hint': '↕ Перетащите, чтобы настроить',
    'taps_unit': ' краны',
  };

  static const Map<String, String> _fr = {
    'settings': 'Réglages',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'share': 'Partager',
    'reset': 'Réinitialiser',
    'done': 'Fait',
    'ok': 'OK',
    'yes': 'Oui',
    'no': 'Non',
    'error': 'Erreur',
    'success': 'Fait',
    'loading': 'Chargement...',
    'no_data': 'Aucune donnée.',
    'no_history': 'Aucun historique.',
    'history': 'Historique',
    'stats': 'Statistiques',
    'refresh': 'Actualiser',
    'bpm': 'temporisation',
    'history_item_subtitle': 'écran : @screen\nroute : @route',
    'total_events': 'Événements totaux',
    'today_events': 'Événements d\'aujourd\'hui',
    'week_events': 'Événements de cette semaine',
    'unique_routes': 'Routes uniques',
    'unique_screens': 'Écrans uniques',
    'top_events': 'Top événements',
    'open_history': 'Historique',
    'open_stats': 'Stats',
    'clear_all': 'Tout effacer',
    'copy': 'Copier',
    'settings_title': 'Réglages',
    'settings_page': 'Réglages',
    'dark_mode': 'Mode sombre',
    'language': 'Langue',
    'about': 'À propos',
    'version': 'Version',
    'rate_app': 'Noter cette app',
    'privacy_policy': 'Confidentialité',
    'remove_ads': 'Supprimer les pubs',
    'premium_title': 'Premium',
    'premium_subtitle':
        'Évitez les publicités et débloquez toutes les fonctionnalités.',
    'premium_benefits': 'Avantages premium',
    'premium_benefit_remove_ads': 'Supprimer les pubs',
    'premium_benefit_unlimited':
        'Utilisez toutes les fonctionnalités sans limites',
    'premium_benefit_statistics': 'Afficher des statistiques supplémentaires',
    'premium_plan_title': 'Choisissez un forfait',
    'premium_plan_weekly': 'Semaine',
    'premium_plan_weekly_desc': '1 semaine d\'accès premium',
    'premium_plan_monthly': 'Mois',
    'premium_plan_monthly_desc': '30 jours d\'accès premium',
    'premium_plan_yearly': 'Annuel',
    'premium_plan_yearly_desc': 'Accès premium pendant 365 jours',
    'premium_purchase': 'Démarrer Premium',
    'premium_restore': 'Restaurer les achats',
    'premium_owned': 'Premium est actif',
    'premium_purchase_note':
        'Si votre paiement est effectué, l\'achat sera automatiquement restauré après le redémarrage de l\'application.',
    'purchase_error':
        'Impossible de terminer l achat. Réessayez dans un instant.',
    'purchase_unavailable':
        'Les achats intégrés ne sont pas disponibles pour le moment. Veuillez réessayer dans un instant.',
    'purchase_failed':
        'Impossible de terminer l achat. Réessayez dans un instant.',
    'restore_error':
        'Impossible de restaurer l achat. Réessayez dans un instant.',
    'purchase_success': 'Achat terminé.',
    'premium_ready': 'La prime est prête.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Envoyer un avis',
    'more_apps': 'Voir plus apps',
    'app_name': 'Métronome',
    'haptic': 'Vibration',
    'sound': 'Son',
    'play': 'Lire',
    'stop': 'Stop',
    'beat_pattern': 'Modèle de battement',
    'tap_tempo': 'Appuyez sur le tempo',
    'tap_for_bpm': 'Appuyez sur le bouton pour trouver le BPM',
    'tap_count_one': '1 pression — appuyez une fois de plus pour mesurer',
    'tap_count_many': 'Robinets @count',
    'guide': 'Guide',
    'guide_title': 'Comment utiliser le métronome',
    'guide_tip_1_title': '1) Réglez le BPM',
    'guide_tip_1_desc':
        'Utilisez le curseur ou les boutons +/- pour définir le tempo souhaité.',
    'guide_tip_2_title': '2) Choisissez un motif de rythme',
    'guide_tip_2_desc':
        'Modifiez le motif de battement pour qu\'il corresponde au style que vous souhaitez pratiquer.',
    'guide_tip_3_title': '3) Enregistrez votre préférence',
    'guide_tip_3_desc':
        'Activez ou désactivez les vibrations et conservez vos paramètres de tempo et de rythme préférés.',
    'guide_tip_4_title': '4) Consulter l\'historique',
    'guide_tip_4_desc':
        'Vérifiez votre utilisation du métronome dans l\'historique et les statistiques.',
    'guide_tip_5_title': '5) Subdivisions',
    'guide_tip_5_desc':
        'Divisez chaque battement en croches, triolets ou doubles croches pour un entraînement précis.',
    'guide_tip_6_title': '6) Motifs d\'accentuation',
    'guide_tip_6_desc':
        'Appuyez sur n\'importe quel indicateur de battement pour parcourir les accents forts, normaux et muets.',
    'guide_tip_7_title': '7) Faites glisser pour changer le BPM',
    'guide_tip_7_desc':
        'Faites glisser votre doigt vers le haut ou vers le bas sur l\'écran BPM pour régler rapidement le tempo.',
    'guide_footer':
        'Vous pouvez tout régler en un seul clic depuis Accueil et l\'utiliser immédiatement.',
    'subdivision': 'Subdivision',
    'drag_bpm_hint': '↕ Faites glisser pour ajuster',
    'taps_unit': ' robinets',
  };

  static const Map<String, String> _es = {
    'settings': 'Ajustes',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'delete': 'Eliminar',
    'edit': 'Editar',
    'share': 'Compartir',
    'reset': 'Reiniciar',
    'done': 'Hechas',
    'ok': 'OK',
    'yes': 'Sí',
    'no': 'No',
    'error': 'Error',
    'success': 'Hechas',
    'loading': 'Cargando...',
    'no_data': 'Aún no hay datos.',
    'no_history': 'Aún no hay historial.',
    'history': 'Historial',
    'stats': 'Estadísticas',
    'refresh': 'Actualizar',
    'bpm': 'BPM',
    'history_item_subtitle': 'pantalla: @screen\nruta: @route',
    'total_events': 'Eventos totales',
    'today_events': 'Eventos de hoy',
    'week_events': 'Eventos de esta semana',
    'unique_routes': 'Rutas únicas',
    'unique_screens': 'Pantallas únicas',
    'top_events': 'Eventos principales',
    'open_history': 'Historial',
    'open_stats': 'Estadísticas',
    'clear_all': 'Borrar todo',
    'copy': 'Copiar',
    'settings_title': 'Ajustes',
    'settings_page': 'Ajustes',
    'dark_mode': 'Modo oscuro',
    'language': 'Idioma',
    'about': 'Acerca de',
    'version': 'Versión',
    'rate_app': 'Calificar app',
    'privacy_policy': 'Privacidad',
    'remove_ads': 'Quitar anuncios',
    'premium_title': 'Premium',
    'premium_subtitle': 'No tenga publicidad y desbloquee todas las funciones.',
    'premium_benefits': 'Beneficios Premium',
    'premium_benefit_remove_ads': 'Quitar anuncios',
    'premium_benefit_unlimited': 'Utilice todas las funciones sin límites',
    'premium_benefit_statistics': 'Ver estadísticas adicionales',
    'premium_plan_title': 'Elige un plan',
    'premium_plan_weekly': 'Semana',
    'premium_plan_weekly_desc': 'Acceso premium de 1 semana',
    'premium_plan_monthly': 'Mes',
    'premium_plan_monthly_desc': 'Acceso premium de 30 días',
    'premium_plan_yearly': 'Anual',
    'premium_plan_yearly_desc': 'Acceso premium de 365 días',
    'premium_purchase': 'Iniciar prima',
    'premium_restore': 'Restaurar compras',
    'premium_owned': 'Premium está activo',
    'premium_purchase_note':
        'Si se completa su pago, la compra se restaurará automáticamente después de reiniciar la aplicación.',
    'purchase_error':
        'No se pudo completar la compra. Inténtalo de nuevo pronto.',
    'purchase_unavailable':
        'Las compras dentro de la aplicación no están disponibles en este momento. Inténtelo de nuevo en un momento.',
    'purchase_failed':
        'No se pudo completar la compra. Inténtalo de nuevo pronto.',
    'restore_error':
        'No se pudo restaurar la compra. Inténtalo de nuevo pronto.',
    'purchase_success': 'Compra completa.',
    'premium_ready': 'La prima está lista.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Enviar opinión',
    'more_apps': 'Ver más apps',
    'app_name': 'metrónomo',
    'haptic': 'Vibración',
    'sound': 'Sonido',
    'play': 'Reproducir',
    'stop': 'Parar',
    'beat_pattern': 'Patrón de ritmo',
    'tap_tempo': 'Toque el tempo',
    'tap_for_bpm': 'Toque el botón para encontrar el BPM',
    'tap_count_one': '1 toque: toque una vez más para medir',
    'tap_count_many': 'grifos @count',
    'guide': 'Guía',
    'guide_title': 'Cómo usar el metrónomo',
    'guide_tip_1_title': '1) Establecer los BPM',
    'guide_tip_1_desc':
        'Utilice el control deslizante o los botones +/- para establecer el tempo que desee.',
    'guide_tip_2_title': '2) Elige un patrón de ritmo',
    'guide_tip_2_desc':
        'Cambia el patrón de ritmo para que coincida con el estilo que deseas practicar.',
    'guide_tip_3_title': '3) Guarda tu preferencia',
    'guide_tip_3_desc':
        'Active o desactive la vibración y mantenga su ritmo y configuración de ritmo preferidos.',
    'guide_tip_4_title': '4) Revisar el historial',
    'guide_tip_4_desc':
        'Verifique el uso de su metrónomo en Historial y Estadísticas.',
    'guide_tip_5_title': '5) Subdivisiones',
    'guide_tip_5_desc':
        'Divide cada tiempo en corcheas, tresillos o semicorcheas para una práctica precisa.',
    'guide_tip_6_title': '6) Patrones de acento',
    'guide_tip_6_desc':
        'Toque cualquier indicador de ritmo para alternar entre acentos fuertes, normales y mudos.',
    'guide_tip_7_title': '7) Arrastra para cambiar BPM',
    'guide_tip_7_desc':
        'Desliza hacia arriba o hacia abajo en la pantalla BPM para ajustar rápidamente el tempo.',
    'guide_footer':
        'Puedes ajustar todo con un solo toque desde Inicio y usarlo inmediatamente.',
    'subdivision': 'Subdivisión',
    'drag_bpm_hint': '↕ Arrastra para ajustar',
    'taps_unit': ' grifos',
  };

  static const Map<String, String> _pt = {
    'settings': 'Configurações',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'delete': 'Excluir',
    'edit': 'Editar',
    'share': 'Compartilhar',
    'reset': 'Redefinir',
    'done': 'Feitas',
    'ok': 'OK',
    'yes': 'Sim',
    'no': 'Não',
    'error': 'Erro',
    'success': 'Feitas',
    'loading': 'Carregando...',
    'no_data': 'Ainda sem dados.',
    'no_history': 'Ainda sem histórico.',
    'history': 'Histórico',
    'stats': 'Estatísticas',
    'refresh': 'Atualizar',
    'bpm': 'BPM',
    'history_item_subtitle': 'tela: @screen\nrota: @route',
    'total_events': 'Total de eventos',
    'today_events': 'Eventos de hoje',
    'week_events': 'Eventos desta semana',
    'unique_routes': 'Rotas únicas',
    'unique_screens': 'Telas únicas',
    'top_events': 'Principais eventos',
    'open_history': 'Histórico',
    'open_stats': 'Estatísticas',
    'clear_all': 'Limpar tudo',
    'copy': 'Copiar',
    'settings_title': 'Configurações',
    'settings_page': 'Configurações',
    'dark_mode': 'Modo escuro',
    'language': 'Idioma',
    'about': 'Sobre',
    'version': 'Versão',
    'rate_app': 'Avaliar app',
    'privacy_policy': 'Privacidade',
    'remove_ads': 'Remover anúncios',
    'premium_title': 'Premium',
    'premium_subtitle': 'Fique sem anúncios e desbloqueie todos os recursos.',
    'premium_benefits': 'Benefícios Premium',
    'premium_benefit_remove_ads': 'Remover anúncios',
    'premium_benefit_unlimited': 'Use todos os recursos sem limites',
    'premium_benefit_statistics': 'Ver estatísticas adicionais',
    'premium_plan_title': 'Escolha um plano',
    'premium_plan_weekly': 'Semana',
    'premium_plan_weekly_desc': '1 semana de acesso premium',
    'premium_plan_monthly': 'Mês',
    'premium_plan_monthly_desc': '30 dias de acesso premium',
    'premium_plan_yearly': 'Anualmente',
    'premium_plan_yearly_desc': 'Acesso premium de 365 dias',
    'premium_purchase': 'Iniciar Premium',
    'premium_restore': 'Restaurar compras',
    'premium_owned': 'Premium está ativo',
    'premium_purchase_note':
        'Se o seu pagamento for concluído, a compra será restaurada automaticamente após a reinicialização do aplicativo.',
    'purchase_error':
        'Não foi possível concluir a compra. Tente novamente em instantes.',
    'purchase_unavailable':
        'As compras no aplicativo não estão disponíveis no momento. Por favor, tente novamente em alguns instantes.',
    'purchase_failed':
        'Não foi possível concluir a compra. Tente novamente em instantes.',
    'restore_error':
        'Não foi possível restaurar a compra. Tente novamente em instantes.',
    'purchase_success': 'Compra concluída.',
    'premium_ready': 'O prêmio está pronto.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Enviar feedback',
    'more_apps': 'Ver mais apps',
    'app_name': 'Metrônomo',
    'haptic': 'Vibração',
    'sound': 'Som',
    'play': 'Reproduzir',
    'stop': 'Parar',
    'beat_pattern': 'Padrão de batida',
    'tap_tempo': 'Toque em Tempo',
    'tap_for_bpm': 'Toque no botão para encontrar o BPM',
    'tap_count_one': '1 toque – toque mais uma vez para medir',
    'tap_count_many': 'Torneiras @count',
    'guide': 'Guia',
    'guide_title': 'Como usar o metrônomo',
    'guide_tip_1_title': '1) Defina o BPM',
    'guide_tip_1_desc':
        'Use o controle deslizante ou os botões +/- para definir o andamento desejado.',
    'guide_tip_2_title': '2) Escolha um padrão de batida',
    'guide_tip_2_desc':
        'Altere o padrão de batida para combinar com o estilo que deseja praticar.',
    'guide_tip_3_title': '3) Salve sua preferência',
    'guide_tip_3_desc':
        'Ative ou desative a vibração e mantenha suas configurações preferidas de ritmo e batida.',
    'guide_tip_4_title': '4) Revise o histórico',
    'guide_tip_4_desc':
        'Verifique o uso do metrônomo em Histórico e Estatísticas.',
    'guide_tip_5_title': '5) Subdivisões',
    'guide_tip_5_desc':
        'Divida cada batida em colcheias, tercinas ou semicolcheias para uma prática precisa.',
    'guide_tip_6_title': '6) Padrões de acento',
    'guide_tip_6_desc':
        'Toque em qualquer indicador de batida para alternar entre acentos fortes, normais e mudos.',
    'guide_tip_7_title': '7) Arraste para alterar o BPM',
    'guide_tip_7_desc':
        'Deslize para cima ou para baixo na tela BPM para ajustar rapidamente o andamento.',
    'guide_footer':
        'Você pode ajustar tudo com um toque na página inicial e usá-lo imediatamente.',
    'subdivision': 'Subdivisão',
    'drag_bpm_hint': '↕ Arraste para ajustar',
    'taps_unit': ' torneiras',
  };

  static const Map<String, String> _id = {
    'settings': 'Pengaturan',
    'save': 'Simpan',
    'cancel': 'Batal',
    'delete': 'Hapus',
    'edit': 'Edit',
    'share': 'Bagikan',
    'reset': 'Reset',
    'done': 'Selesai',
    'ok': 'OK',
    'yes': 'Ya',
    'no': 'Tidak',
    'error': 'Error',
    'success': 'Selesai',
    'loading': 'Memuat...',
    'no_data': 'Belum ada data.',
    'no_history': 'Belum ada riwayat.',
    'history': 'Riwayat',
    'stats': 'Statistik',
    'refresh': 'Muat ulang',
    'bpm': 'BPM',
    'history_item_subtitle': 'layar: @screen\nrute: @route',
    'total_events': 'Total event',
    'today_events': 'Event hari ini',
    'week_events': 'Acara Minggu Ini',
    'unique_routes': 'Rute unik',
    'unique_screens': 'Layar unik',
    'top_events': 'Event teratas',
    'open_history': 'Riwayat',
    'open_stats': 'Statistik',
    'clear_all': 'Hapus semua',
    'copy': 'Salin',
    'settings_title': 'Pengaturan',
    'settings_page': 'Pengaturan',
    'dark_mode': 'Mode gelap',
    'language': 'Bahasa',
    'about': 'Tentang',
    'version': 'Versi',
    'rate_app': 'Beri rating',
    'privacy_policy': 'Privasi',
    'remove_ads': 'Hapus iklan',
    'premium_title': 'Premium',
    'premium_subtitle': 'Bebas iklan dan buka semua fitur.',
    'premium_benefits': 'Manfaat Premi',
    'premium_benefit_remove_ads': 'Hapus iklan',
    'premium_benefit_unlimited': 'Gunakan semua fitur tanpa batas',
    'premium_benefit_statistics': 'Lihat statistik tambahan',
    'premium_plan_title': 'Pilih rencana',
    'premium_plan_weekly': 'Mingguan',
    'premium_plan_weekly_desc': 'Akses premium 1 minggu',
    'premium_plan_monthly': 'Bulanan',
    'premium_plan_monthly_desc': 'Akses premium 30 hari',
    'premium_plan_yearly': 'Tahunan',
    'premium_plan_yearly_desc': 'Akses premium 365 hari',
    'premium_purchase': 'Mulai Premium',
    'premium_restore': 'Pulihkan pembelian',
    'premium_owned': 'Premium aktif',
    'premium_purchase_note':
        'Jika pembayaran Anda selesai, pembelian akan dikembalikan secara otomatis setelah aplikasi dimulai ulang.',
    'purchase_error': 'Pembelian belum selesai. Coba lagi sebentar lagi.',
    'purchase_unavailable':
        'Pembelian dalam aplikasi tidak tersedia saat ini. Silakan coba lagi sebentar lagi.',
    'purchase_failed': 'Pembelian belum selesai. Coba lagi sebentar lagi.',
    'restore_error':
        'Pembelian belum bisa dipulihkan. Coba lagi sebentar lagi.',
    'purchase_success': 'Pembelian selesai.',
    'premium_ready': 'Premi sudah siap.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Kirim masukan',
    'more_apps': 'Lihat aplikasi lain',
    'app_name': 'Metronom',
    'haptic': 'Getaran',
    'sound': 'Suara',
    'play': 'Putar',
    'stop': 'Stop',
    'beat_pattern': 'Pola Ketukan',
    'tap_tempo': 'Ketuk Tempo',
    'tap_for_bpm': 'Ketuk tombol untuk menemukan BPM',
    'tap_count_one': '1 ketuk — ketuk sekali lagi untuk mengukur',
    'tap_count_many': '@count mengetuk',
    'guide': 'Panduan',
    'guide_title': 'Cara menggunakan metronom',
    'guide_tip_1_title': '1) Atur BPMnya',
    'guide_tip_1_desc':
        'Gunakan tombol penggeser atau +/- untuk mengatur tempo yang Anda inginkan.',
    'guide_tip_2_title': '2) Pilih pola irama',
    'guide_tip_2_desc':
        'Ubah pola irama agar sesuai dengan gaya yang ingin Anda latih.',
    'guide_tip_3_title': '3) Simpan preferensi Anda',
    'guide_tip_3_desc':
        'Nyalakan atau matikan getaran dan pertahankan pengaturan tempo dan ketukan pilihan Anda.',
    'guide_tip_4_title': '4) Tinjau sejarah',
    'guide_tip_4_desc':
        'Periksa penggunaan metronom Anda di Riwayat dan Statistik.',
    'guide_tip_5_title': '5) Subbagian',
    'guide_tip_5_desc':
        'Bagi setiap ketukan menjadi nada kedelapan, kembar tiga, atau nada keenam belas untuk latihan yang tepat.',
    'guide_tip_6_title': '6) Pola aksen',
    'guide_tip_6_desc':
        'Ketuk indikator ketukan mana pun untuk beralih melalui aksen kuat, normal, dan senyap.',
    'guide_tip_7_title': '7) Seret untuk mengubah BPM',
    'guide_tip_7_desc':
        'Gesek ke atas atau ke bawah pada tampilan BPM untuk menyesuaikan tempo dengan cepat.',
    'guide_footer':
        'Anda dapat menyesuaikan semuanya dalam satu ketukan dari Rumah dan segera menggunakannya.',
    'subdivision': 'Subdivisi',
    'drag_bpm_hint': '↕ Tarik untuk menyesuaikan',
    'taps_unit': ' keran',
  };

  static const Map<String, String> _zh = {
    'settings': '设置',
    'save': '保存',
    'cancel': '取消',
    'delete': '删除',
    'edit': '编辑',
    'share': '分享',
    'reset': '重置',
    'done': '已完成',
    'ok': '确定',
    'yes': '是',
    'no': '否',
    'error': '错误',
    'success': '已完成',
    'loading': '加载中...',
    'no_data': '暂无数据。',
    'no_history': '暂无记录。',
    'history': '记录',
    'stats': '统计',
    'refresh': '刷新',
    'bpm': '业务流程管理',
    'history_item_subtitle': '页面: @screen\n路由: @route',
    'total_events': '事件总数',
    'today_events': '今日事件',
    'week_events': '本周活动',
    'unique_routes': '唯一路径',
    'unique_screens': '唯一页面',
    'top_events': '热门事件',
    'open_history': '记录',
    'open_stats': '统计',
    'clear_all': '全部清除',
    'copy': '复制',
    'settings_title': '设置',
    'settings_page': '设置',
    'dark_mode': '深色模式',
    'language': '语言',
    'about': '关于',
    'version': '版本',
    'rate_app': '评价应用',
    'privacy_policy': '隐私政策',
    'remove_ads': '移除广告',
    'premium_title': '高级',
    'premium_subtitle': '无广告并解锁所有功能。',
    'premium_benefits': '高级福利',
    'premium_benefit_remove_ads': '移除广告',
    'premium_benefit_unlimited': '无限制地使用所有功能',
    'premium_benefit_statistics': '查看更多统计数据',
    'premium_plan_title': '选择一个计划',
    'premium_plan_weekly': '每周',
    'premium_plan_weekly_desc': '1 周高级访问权限',
    'premium_plan_monthly': '每月',
    'premium_plan_monthly_desc': '30 天高级访问权限',
    'premium_plan_yearly': '每年',
    'premium_plan_yearly_desc': '365 天高级访问',
    'premium_purchase': '启动高级版',
    'premium_restore': '恢复购买',
    'premium_owned': 'Premium 已激活',
    'premium_purchase_note': '如果您的付款完成，应用重启后将自动恢复购买。',
    'purchase_error': '无法完成购买。请稍后再试。',
    'purchase_unavailable': '目前无法进行应用内购买。请稍后重试。',
    'purchase_failed': '无法完成购买。请稍后再试。',
    'restore_error': '无法恢复购买。请稍后再试。',
    'purchase_success': '购买完成。',
    'premium_ready': '高级版已准备就绪。',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': '发送反馈',
    'more_apps': '查看更多应用',
    'app_name': '节拍器',
    'haptic': '振动',
    'sound': '声音',
    'play': '播放',
    'stop': '停止',
    'beat_pattern': '节拍模式',
    'tap_tempo': '敲击节奏',
    'tap_for_bpm': '点击按钮即可找到 BPM',
    'tap_count_one': '点击 1 次 — 再次点击进行测量',
    'tap_count_many': '@count 丝锥',
    'guide': '引导',
    'guide_title': '如何使用节拍器',
    'guide_tip_1_title': '1) 设置节拍数',
    'guide_tip_1_desc': '使用滑块或 +/- 按钮设置您想要的速度。',
    'guide_tip_2_title': '2) 选择节拍模式',
    'guide_tip_2_desc': '更改节拍模式以匹配您想要练习的风格。',
    'guide_tip_3_title': '3) 保存您的偏好',
    'guide_tip_3_desc': '打开或关闭振动并保持您喜欢的节奏和节拍设置。',
    'guide_tip_4_title': '4) 回顾历史',
    'guide_tip_4_desc': '在历史记录和统计数据中检查节拍器的使用情况。',
    'guide_tip_5_title': '5）细分',
    'guide_tip_5_desc': '将每个节拍分成八分音符、三连音或十六分音符，以便精确练习。',
    'guide_tip_6_title': '6) 强调图案',
    'guide_tip_6_desc': '点击任何节拍指示器即可在重音、正常重音和静音重音之间循环。',
    'guide_tip_7_title': '7) 拖动改变BPM',
    'guide_tip_7_desc': '在 BPM 显示屏上向上或向下滑动即可快速调整速度。',
    'guide_footer': '您可以从主页一键调整所有内容并立即使用。',
    'subdivision': '细分',
    'drag_bpm_hint': '↕ 拖动调整',
    'taps_unit': ' 水龙头',
  };

  static const Map<String, String> _ar = {
    'settings': 'الإعدادات',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'share': 'مشاركة',
    'reset': 'إعادة ضبط',
    'done': 'منجز',
    'ok': 'حسناً',
    'yes': 'نعم',
    'no': 'لا',
    'error': 'خطأ',
    'success': 'منجز',
    'loading': 'جار التحميل...',
    'no_data': 'لا توجد بيانات بعد.',
    'no_history': 'لا يوجد سجل بعد.',
    'history': 'السجل',
    'stats': 'الإحصاءات',
    'refresh': 'تحديث',
    'bpm': 'بي بي إم',
    'history_item_subtitle': 'الشاشة: @screen\nالمسار: @route',
    'total_events': 'إجمالي الأحداث',
    'today_events': 'أحداث اليوم',
    'week_events': 'أحداث هذا الأسبوع',
    'unique_routes': 'مسارات فريدة',
    'unique_screens': 'شاشات فريدة',
    'top_events': 'أهم الأحداث',
    'open_history': 'السجل',
    'open_stats': 'الإحصاءات',
    'clear_all': 'مسح الكل',
    'copy': 'نسخ',
    'settings_title': 'الإعدادات',
    'settings_page': 'الإعدادات',
    'dark_mode': 'الوضع الداكن',
    'language': 'اللغة',
    'about': 'حول التطبيق',
    'version': 'الإصدار',
    'rate_app': 'تقييم التطبيق',
    'privacy_policy': 'سياسة الخصوصية',
    'remove_ads': 'إزالة الإعلانات',
    'premium_title': 'مميز',
    'premium_subtitle':
        'استمتع بالإعلانات الخالية من الإعلانات وافتح جميع الميزات.',
    'premium_benefits': 'فوائد متميزة',
    'premium_benefit_remove_ads': 'إزالة الإعلانات',
    'premium_benefit_unlimited': 'استخدم كافة الميزات بلا حدود',
    'premium_benefit_statistics': 'عرض إحصائيات إضافية',
    'premium_plan_title': 'اختر خطة',
    'premium_plan_weekly': 'أسبوعي',
    'premium_plan_weekly_desc': 'وصول مميز لمدة أسبوع واحد',
    'premium_plan_monthly': 'شهري',
    'premium_plan_monthly_desc': 'وصول مميز لمدة 30 يومًا',
    'premium_plan_yearly': 'سنويا',
    'premium_plan_yearly_desc': 'وصول مميز لمدة 365 يومًا',
    'premium_purchase': 'ابدأ بريميوم',
    'premium_restore': 'استعادة المشتريات',
    'premium_owned': 'Premium نشط',
    'premium_purchase_note':
        'إذا اكتملت عملية الدفع، فستتم استعادة عملية الشراء تلقائيًا بعد إعادة تشغيل التطبيق.',
    'purchase_error': 'تعذر إكمال الشراء. حاول بعد قليل.',
    'purchase_unavailable':
        'عمليات الشراء داخل التطبيق غير متاحة حاليًا. الرجاء المحاولة مرة أخرى في لحظة.',
    'purchase_failed': 'تعذر إكمال الشراء. حاول بعد قليل.',
    'restore_error': 'تعذر استعادة الشراء. حاول بعد قليل.',
    'purchase_success': 'اكتمل الشراء.',
    'premium_ready': 'قسط جاهز.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'إرسال ملاحظات',
    'more_apps': 'عرض المزيد من التطبيقات',
    'app_name': 'المسرع',
    'haptic': 'الاهتزاز',
    'sound': 'الصوت',
    'play': 'تشغيل',
    'stop': 'إيقاف',
    'beat_pattern': 'نمط الفوز',
    'tap_tempo': 'اضغط على الإيقاع',
    'tap_for_bpm': 'اضغط على الزر للعثور على BPM',
    'tap_count_one': 'نقرة واحدة — انقر مرة أخرى للقياس',
    'tap_count_many': 'الصنابير @count',
    'guide': 'الدليل',
    'guide_title': 'كيفية استخدام المسرع',
    'guide_tip_1_title': '1) ضبط BPM',
    'guide_tip_1_desc':
        'استخدم شريط التمرير أو أزرار +/- لضبط الإيقاع الذي تريده.',
    'guide_tip_2_title': '2) اختر نمط الإيقاع',
    'guide_tip_2_desc':
        'قم بتغيير نمط الإيقاع ليتناسب مع النمط الذي تريد التدرب عليه.',
    'guide_tip_3_title': '3) احفظ تفضيلاتك',
    'guide_tip_3_desc':
        'قم بتشغيل الاهتزاز أو إيقافه وحافظ على إعدادات الإيقاع والإيقاع المفضلة لديك.',
    'guide_tip_4_title': '4) مراجعة التاريخ',
    'guide_tip_4_desc':
        'تحقق من استخدام بندول الإيقاع الخاص بك في التاريخ والإحصائيات.',
    'guide_tip_5_title': '5) التقسيمات الفرعية',
    'guide_tip_5_desc':
        'قم بتقسيم كل نغمة إلى نغمات ثامنة أو ثلاثية أو نغمات سادسة عشرة للتمرين الدقيق.',
    'guide_tip_6_title': '6) أنماط اللكنة',
    'guide_tip_6_desc':
        'اضغط على أي مؤشر إيقاع للتنقل بين اللهجات القوية والعادية والصامتة.',
    'guide_tip_7_title': '7) اسحب لتغيير BPM',
    'guide_tip_7_desc': 'اسحب لأعلى أو لأسفل على شاشة BPM لضبط الإيقاع بسرعة.',
    'guide_footer':
        'يمكنك ضبط كل شيء بنقرة واحدة من الصفحة الرئيسية واستخدامه على الفور.',
    'subdivision': 'التقسيم',
    'drag_bpm_hint': '↕ اسحب للضبط',
    'taps_unit': ' الصنابير',
  };
}
